version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - ireturn
    - mnd
    - nilnil
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      severity: warning
      enable-all-rules: false
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: true
      context: scope
      static-msg: true
      key-naming-case: snake
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - golint
          - revive
        text: should have a package comment
      - linters:
          - dupl
          - gosec
          - wrapcheck
        path: _test\.go
      - linters:
          - dupl
          - gosec
          - wrapcheck
        path: e2e/.*\.go
      - linters:
          - gochecknoinits
        path: cmd/.*\.go
    paths:
      - vendor
      - pkg/gen
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/leonardinius/go-service-template)
        - blank
        - dot
        - alias
  exclusions:
    generated: lax
    paths:
      - vendor
      - pkg/gen
      - third_party$
      - builtin$
      - examples$
