package version

var (
	// ServiceName represents the name of the service.
	ServiceName = "{{service}}"

	// RefName represents a reference name.
	RefName = "{{dirty}}"

	// Commit represents the SHA-1 hash of the current git commit.
	Commit = "{{gitsha1}}"

	// BuildTime represents the timestamp of when the build occurred.
	BuildTime = "{{buildtime}}"

	// FullVersion represents the full version of the service,
	//  generated by concatenating the values of RefName, Commit, and BuildTime.
	//  It follows the format RefName@vCommit-BuildTime.
	FullVersion = RefName + "-" + BuildTime + "@" + Commit
)
