// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/type/datetime.proto

package _type

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DateTime with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DateTime) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DateTime with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DateTimeMultiError, or nil
// if none found.
func (m *DateTime) ValidateAll() error {
	return m.validate(true)
}

func (m *DateTime) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Year

	// no validation rules for Month

	// no validation rules for Day

	// no validation rules for Hours

	// no validation rules for Minutes

	// no validation rules for Seconds

	// no validation rules for Nanos

	switch v := m.TimeOffset.(type) {
	case *DateTime_UtcOffset:
		if v == nil {
			err := DateTimeValidationError{
				field:  "TimeOffset",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetUtcOffset()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DateTimeValidationError{
						field:  "UtcOffset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DateTimeValidationError{
						field:  "UtcOffset",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetUtcOffset()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DateTimeValidationError{
					field:  "UtcOffset",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *DateTime_TimeZone:
		if v == nil {
			err := DateTimeValidationError{
				field:  "TimeOffset",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetTimeZone()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DateTimeValidationError{
						field:  "TimeZone",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DateTimeValidationError{
						field:  "TimeZone",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimeZone()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DateTimeValidationError{
					field:  "TimeZone",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return DateTimeMultiError(errors)
	}

	return nil
}

// DateTimeMultiError is an error wrapping multiple validation errors returned
// by DateTime.ValidateAll() if the designated constraints aren't met.
type DateTimeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DateTimeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DateTimeMultiError) AllErrors() []error { return m }

// DateTimeValidationError is the validation error returned by
// DateTime.Validate if the designated constraints aren't met.
type DateTimeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DateTimeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DateTimeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DateTimeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DateTimeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DateTimeValidationError) ErrorName() string { return "DateTimeValidationError" }

// Error satisfies the builtin error interface
func (e DateTimeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDateTime.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DateTimeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DateTimeValidationError{}

// Validate checks the field values on TimeZone with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TimeZone) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TimeZone with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TimeZoneMultiError, or nil
// if none found.
func (m *TimeZone) ValidateAll() error {
	return m.validate(true)
}

func (m *TimeZone) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Version

	if len(errors) > 0 {
		return TimeZoneMultiError(errors)
	}

	return nil
}

// TimeZoneMultiError is an error wrapping multiple validation errors returned
// by TimeZone.ValidateAll() if the designated constraints aren't met.
type TimeZoneMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TimeZoneMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TimeZoneMultiError) AllErrors() []error { return m }

// TimeZoneValidationError is the validation error returned by
// TimeZone.Validate if the designated constraints aren't met.
type TimeZoneValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TimeZoneValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TimeZoneValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TimeZoneValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TimeZoneValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TimeZoneValidationError) ErrorName() string { return "TimeZoneValidationError" }

// Error satisfies the builtin error interface
func (e TimeZoneValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTimeZone.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TimeZoneValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TimeZoneValidationError{}
